### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by erikbrandondigital** [erikbrandondigital/ready-set-travel#12]
Complete the following tasks:
- [x] `dev > readysettravel` folder should contain a template.html file.
- [x] Add Iconify Icons to project index.html and replace image icons with Iconify Icons and remove image icons.
- [x] Implement BEM CSS naming convention in CSS files.
- [x] Refined & refactored existing code and noted changes in commit history and changelog.
- [x] In `docs` create a file called Milestone2-Changelog.md & update it with changes.
- [x] Commit at least 4 changes to the repo over 4 days.
- [x] Complete the Milestone 2 Week 2 standup.
- [x] Post link to Repo in 2.7 Milestone 2 assignment.
