### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by erikbrandondigital** [erikbrandondigital/ready-set-travel#15]
Complete The Following Tasks:
- [x] Build the following secondary remaining pages of the site:
    - [x] About Us
    - [x] Blog
    - [x] Destinations
    - [x] Tours
- [x] Create and update a Milestone3-Changelog.md file in the `docs` folder 
- [x] Make at least 4 commits over a series of days to this repo.
- [x] Validate all modified HTML & CSS files and add screenshots of each to `docs > validation` folder.
- [x] Add Milestone 3 Standup to README.md file.
