### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by erikbrandondigital** [erikbrandondigital/ready-set-travel#20]
Complete the following tasks:
- [x] Add a Milestone4-Changelog.md file to the docs folder & document any changes made in Week 4.
- [x] Validate all modified HTML & CSS files and add screenshots of results to the repo.
- [x] Create at least four issues in GitHub & update them during the week.
- [x] Make at least four commits to this repo.
- [x] Add the final standup to the README.md file.
